// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shared.Infrastructure.Data.HrmDbContext;

#nullable disable

namespace Shared.Infrastructure.Migrations.HrmMigration
{
    [DbContext(typeof(HrmDbContext))]
    partial class HrmDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Security.Domain.Entities.Application", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("applications", "userManagement");

                    b.HasData(
                        new
                        {
                            Id = new Guid("89de1083-5d8b-401c-8914-7f6cc1363fdf"),
                            Code = 0,
                            Desc = "Identity & Access Management for the SaaS platform",
                            Name = "User Management"
                        });
                });

            modelBuilder.Entity("UserManagement.Domain.Entities.Agent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<Guid?>("EntryByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsParent")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Pan")
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("ReferralCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RegNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ToDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("VerificationStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ReferralCode")
                        .IsUnique()
                        .HasFilter("[ReferralCode] IS NOT NULL");

                    b.ToTable("agents", "userManagement");

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            Address = "Kathmandu, Nepal",
                            CompanyId = 1,
                            EntryDate = new DateTime(2026, 7, 23, 6, 27, 39, 628, DateTimeKind.Utc).AddTicks(3465),
                            IsParent = true,
                            Name = "Head Office",
                            Pan = "123456789",
                            ReferralCode = "REG-001--1",
                            RegNo = "REG-001",
                            VerificationStatus = 0
                        });
                });

            modelBuilder.Entity("UserManagement.Domain.Entities.AgentRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AgentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<Guid?>("EntryByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ToDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("VerificationStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("RoleId");

                    b.ToTable("agent_roles", "userManagement");
                });

            modelBuilder.Entity("UserManagement.Domain.Entities.AgentUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ToDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("UserId");

                    b.ToTable("agent_users", "userManagement");
                });

            modelBuilder.Entity("UserManagement.Domain.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ProductCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Url")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Pan")
                        .IsUnique();

                    b.HasIndex("RegNo")
                        .IsUnique();

                    b.ToTable("companies", "userManagement");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Kathmandu, Nepal",
                            Email = "info@arsuhrm.com",
                            Name = "ArsuHrm Solutions Pvt. Ltd.",
                            Pan = "123456789",
                            PhoneNo = "9829967841",
                            ProductCode = "HRM",
                            RegNo = "REG-001",
                            Url = "https://arsuhrm.com"
                        });
                });

            modelBuilder.Entity("UserManagement.Domain.Entities.CompanyRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<Guid?>("EntryByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ToDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("VerificationStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("RoleId");

                    b.ToTable("company_roles", "userManagement");
                });

            modelBuilder.Entity("UserManagement.Domain.Entities.LoginLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientAgent")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<DateTime>("LoginDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MacAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OS")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("login_logs", "userManagement");
                });

            modelBuilder.Entity("UserManagement.Domain.Entities.Menu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Icon")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MenuText")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("OrderNo")
                        .HasColumnType("int");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ToolTip")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Url")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("menus", "userManagement");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9a71e39c-1e80-423e-9d87-16586687575f"),
                            Active = true,
                            Color = "red",
                            Icon = "FaShieldHalved",
                            MenuText = "User Management",
                            OrderNo = 1,
                            ToolTip = "User Management"
                        },
                        new
                        {
                            Id = new Guid("6a7b8c9d-0e1f-4a2b-8c9d-0e1f2a3b4c5d"),
                            Active = true,
                            Color = "purple",
                            Icon = "FaBuilding",
                            MenuText = "Company Role",
                            OrderNo = 1,
                            ParentId = new Guid("9a71e39c-1e80-423e-9d87-16586687575f"),
                            ToolTip = "Company Role Management",
                            Url = "/UserManagement/company-role"
                        },
                        new
                        {
                            Id = new Guid("45bda341-5e70-495c-aecd-075efef1885b"),
                            Active = true,
                            Color = "blue",
                            Icon = "FaUsersGear",
                            MenuText = "Collection Center Role",
                            OrderNo = 2,
                            ParentId = new Guid("9a71e39c-1e80-423e-9d87-16586687575f"),
                            ToolTip = "Role for Collection and Distribution Center Management",
                            Url = "/UserManagement/agent-role"
                        },
                        new
                        {
                            Id = new Guid("37878e39-c706-427e-bc86-0e7d13c76665"),
                            Active = true,
                            Color = "blue",
                            Icon = "FaUserGear",
                            MenuText = "User Role",
                            OrderNo = 3,
                            ParentId = new Guid("9a71e39c-1e80-423e-9d87-16586687575f"),
                            ToolTip = "Role for User Management",
                            Url = "/UserManagement/user-role"
                        },
                        new
                        {
                            Id = new Guid("5f35399e-05b3-42f1-8548-ab31b8cb731c"),
                            Active = true,
                            Color = "blue",
                            Icon = "FaUser",
                            MenuText = "User",
                            OrderNo = 4,
                            ParentId = new Guid("9a71e39c-1e80-423e-9d87-16586687575f"),
                            ToolTip = "User Management",
                            Url = "/UserManagement/user"
                        });
                });

            modelBuilder.Entity("UserManagement.Domain.Entities.Module", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("MenuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ToDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.ToTable("modules", "userManagement");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f7a8b9c0-d1e2-4f3a-8b9c-0d1e2f3a4b5c"),
                            ApplicationId = new Guid("89de1083-5d8b-401c-8914-7f6cc1363fdf"),
                            Code = 1,
                            Description = "Company Role Management",
                            FromDate = new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MenuId = new Guid("6a7b8c9d-0e1f-4a2b-8c9d-0e1f2a3b4c5d"),
                            Name = "CompanyRole"
                        },
                        new
                        {
                            Id = new Guid("e3c916fb-608f-42b3-87db-1c46ae5b5148"),
                            ApplicationId = new Guid("89de1083-5d8b-401c-8914-7f6cc1363fdf"),
                            Code = 2,
                            Description = "Collection Center Role Management",
                            FromDate = new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MenuId = new Guid("45bda341-5e70-495c-aecd-075efef1885b"),
                            Name = "AgentRole"
                        },
                        new
                        {
                            Id = new Guid("ba51d83f-8c02-4fb5-922f-650b945b79b2"),
                            ApplicationId = new Guid("89de1083-5d8b-401c-8914-7f6cc1363fdf"),
                            Code = 3,
                            Description = "User Role Management",
                            FromDate = new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MenuId = new Guid("37878e39-c706-427e-bc86-0e7d13c76665"),
                            Name = "UserRole"
                        },
                        new
                        {
                            Id = new Guid("65d5de5a-3b73-4e45-8775-1b3d6f144268"),
                            ApplicationId = new Guid("89de1083-5d8b-401c-8914-7f6cc1363fdf"),
                            Code = 4,
                            Description = "User Management",
                            FromDate = new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MenuId = new Guid("5f35399e-05b3-42f1-8548-ab31b8cb731c"),
                            Name = "User"
                        });
                });

            modelBuilder.Entity("UserManagement.Domain.Entities.ModulePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ModuleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ModuleId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Permission")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId1");

                    b.HasIndex("ModuleId", "Permission")
                        .IsUnique();

                    b.ToTable("module_permissions", "userManagement");

                    b.HasData(
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000001"),
                            ModuleId = new Guid("f7a8b9c0-d1e2-4f3a-8b9c-0d1e2f3a4b5c"),
                            Permission = 0
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000002"),
                            ModuleId = new Guid("f7a8b9c0-d1e2-4f3a-8b9c-0d1e2f3a4b5c"),
                            Permission = 1
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000003"),
                            ModuleId = new Guid("f7a8b9c0-d1e2-4f3a-8b9c-0d1e2f3a4b5c"),
                            Permission = 2
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000004"),
                            ModuleId = new Guid("f7a8b9c0-d1e2-4f3a-8b9c-0d1e2f3a4b5c"),
                            Permission = 3
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000001"),
                            ModuleId = new Guid("65d5de5a-3b73-4e45-8775-1b3d6f144268"),
                            Permission = 0
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000002"),
                            ModuleId = new Guid("65d5de5a-3b73-4e45-8775-1b3d6f144268"),
                            Permission = 1
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000003"),
                            ModuleId = new Guid("65d5de5a-3b73-4e45-8775-1b3d6f144268"),
                            Permission = 2
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000004"),
                            ModuleId = new Guid("65d5de5a-3b73-4e45-8775-1b3d6f144268"),
                            Permission = 3
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000005"),
                            ModuleId = new Guid("ba51d83f-8c02-4fb5-922f-650b945b79b2"),
                            Permission = 0
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000006"),
                            ModuleId = new Guid("ba51d83f-8c02-4fb5-922f-650b945b79b2"),
                            Permission = 1
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000007"),
                            ModuleId = new Guid("ba51d83f-8c02-4fb5-922f-650b945b79b2"),
                            Permission = 2
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000008"),
                            ModuleId = new Guid("ba51d83f-8c02-4fb5-922f-650b945b79b2"),
                            Permission = 3
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000009"),
                            ModuleId = new Guid("e3c916fb-608f-42b3-87db-1c46ae5b5148"),
                            Permission = 0
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-00000000000a"),
                            ModuleId = new Guid("e3c916fb-608f-42b3-87db-1c46ae5b5148"),
                            Permission = 1
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-00000000000b"),
                            ModuleId = new Guid("e3c916fb-608f-42b3-87db-1c46ae5b5148"),
                            Permission = 2
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-00000000000c"),
                            ModuleId = new Guid("e3c916fb-608f-42b3-87db-1c46ae5b5148"),
                            Permission = 3
                        });
                });

            modelBuilder.Entity("UserManagement.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("EntryByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("ToDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EntryByUserId");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[CompanyId] IS NULL");

                    b.HasIndex("CompanyId", "NormalizedName")
                        .IsUnique()
                        .HasFilter("[CompanyId] IS NOT NULL");

                    b.ToTable("roles", "userManagement");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            CompanyId = 1,
                            ConcurrencyStamp = "fa614657-01d6-4246-a755-6ae33ef70c8c",
                            Desc = "Company owner with full permissions",
                            EntryDate = new DateTime(2026, 7, 23, 6, 27, 39, 669, DateTimeKind.Utc).AddTicks(9363),
                            FromDate = new DateTime(2026, 7, 23, 6, 27, 39, 669, DateTimeKind.Utc).AddTicks(9367),
                            Name = "Owner",
                            NormalizedName = "OWNER"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            CompanyId = 1,
                            ConcurrencyStamp = "921fa3d7-33d9-40f5-ac26-7dc3377e5968",
                            Desc = "Administrator with full access",
                            EntryDate = new DateTime(2026, 7, 23, 6, 27, 39, 670, DateTimeKind.Utc).AddTicks(7598),
                            FromDate = new DateTime(2026, 7, 23, 6, 27, 39, 670, DateTimeKind.Utc).AddTicks(7600),
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            CompanyId = 1,
                            ConcurrencyStamp = "4642257d-dae3-4ae1-9d60-dbc1454be3b5",
                            Desc = "Manager with operational access",
                            EntryDate = new DateTime(2026, 7, 23, 6, 27, 39, 670, DateTimeKind.Utc).AddTicks(7610),
                            FromDate = new DateTime(2026, 7, 23, 6, 27, 39, 670, DateTimeKind.Utc).AddTicks(7611),
                            Name = "Manager",
                            NormalizedName = "MANAGER"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            CompanyId = 1,
                            ConcurrencyStamp = "3f4645e2-7b39-44b6-9c25-d2608024d51e",
                            Desc = "Regular user with limited access",
                            EntryDate = new DateTime(2026, 7, 23, 6, 27, 39, 670, DateTimeKind.Utc).AddTicks(7621),
                            FromDate = new DateTime(2026, 7, 23, 6, 27, 39, 670, DateTimeKind.Utc).AddTicks(7621),
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("UserManagement.Domain.Entities.RoleModulePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ModulePermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RoleId", "ModulePermissionId");

                    b.HasIndex("ModulePermissionId");

                    b.ToTable("role_module_permissions", "userManagement");

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            ModulePermissionId = new Guid("60000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            ModulePermissionId = new Guid("60000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            ModulePermissionId = new Guid("60000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            ModulePermissionId = new Guid("60000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            ModulePermissionId = new Guid("50000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            ModulePermissionId = new Guid("50000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            ModulePermissionId = new Guid("50000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            ModulePermissionId = new Guid("50000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            ModulePermissionId = new Guid("50000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            ModulePermissionId = new Guid("50000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            ModulePermissionId = new Guid("50000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            ModulePermissionId = new Guid("50000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            ModulePermissionId = new Guid("50000000-0000-0000-0000-000000000009")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            ModulePermissionId = new Guid("50000000-0000-0000-0000-00000000000a")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            ModulePermissionId = new Guid("50000000-0000-0000-0000-00000000000b")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            ModulePermissionId = new Guid("50000000-0000-0000-0000-00000000000c")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000002"),
                            ModulePermissionId = new Guid("60000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000002"),
                            ModulePermissionId = new Guid("60000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000002"),
                            ModulePermissionId = new Guid("50000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000002"),
                            ModulePermissionId = new Guid("50000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000002"),
                            ModulePermissionId = new Guid("50000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000002"),
                            ModulePermissionId = new Guid("50000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000002"),
                            ModulePermissionId = new Guid("50000000-0000-0000-0000-000000000009")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000002"),
                            ModulePermissionId = new Guid("50000000-0000-0000-0000-00000000000a")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000003"),
                            ModulePermissionId = new Guid("60000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000003"),
                            ModulePermissionId = new Guid("50000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000003"),
                            ModulePermissionId = new Guid("50000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000003"),
                            ModulePermissionId = new Guid("50000000-0000-0000-0000-000000000009")
                        });
                });

            modelBuilder.Entity("UserManagement.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<Guid?>("EntryByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("EntryByUserId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("CompanyId", "NormalizedEmail")
                        .IsUnique()
                        .HasFilter("[CompanyId] IS NOT NULL AND [NormalizedEmail] IS NOT NULL");

                    b.ToTable("users", "userManagement");

                    b.HasData(
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            AccessFailedCount = 0,
                            CompanyId = 1,
                            ConcurrencyStamp = "19b607a6-3966-4b78-8527-5584d1ea4428",
                            Contact = "9800000001",
                            Email = "admin@arsuhrm.com",
                            EmailConfirmed = false,
                            EntryDate = new DateTime(2026, 7, 23, 6, 27, 39, 679, DateTimeKind.Utc).AddTicks(3420),
                            FailedLoginAttempts = 0,
                            FirstName = "Arman",
                            IsEmailConfirmed = false,
                            LastName = "Shrestha",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@ARSUHRM.COM",
                            NormalizedUserName = "ADMIN.ARSUHRM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "64721ff0-bcec-4cdc-9afd-e15b76104a8b",
                            TwoFactorEnabled = false,
                            UserName = "admin.arsuhrm"
                        });
                });

            modelBuilder.Entity("UserManagement.Domain.Entities.UserModulePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ModulePermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ModulePermissionId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ModulePermissionId");

                    b.HasIndex("ModulePermissionId1");

                    b.HasIndex("UserId", "ModulePermissionId")
                        .IsUnique();

                    b.ToTable("user_module_permissions", "userManagement");
                });

            modelBuilder.Entity("UserManagement.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<Guid?>("EntryByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RoleId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ToDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("VerificationStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("RoleId1");

                    b.HasIndex("UserId", "CompanyId");

                    b.HasIndex("UserId", "RoleId");

                    b.HasIndex("UserId", "RoleId", "CompanyId")
                        .IsUnique()
                        .HasFilter("[CompanyId] IS NOT NULL");

                    b.ToTable("user_roles", "userManagement");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cdf3d4ca-d832-4374-a785-3c514601ffd1"),
                            ApprovedDate = new DateTime(2026, 7, 23, 6, 27, 39, 686, DateTimeKind.Utc).AddTicks(1552),
                            CompanyId = 1,
                            EntryByUserId = new Guid("30000000-0000-0000-0000-000000000001"),
                            EntryDate = new DateTime(2026, 7, 23, 6, 27, 39, 685, DateTimeKind.Utc).AddTicks(7239),
                            IsActive = true,
                            IsApproved = true,
                            IsDeleted = false,
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            UpdatedDate = new DateTime(2026, 7, 23, 6, 27, 39, 686, DateTimeKind.Utc).AddTicks(330),
                            UserId = new Guid("30000000-0000-0000-0000-000000000001"),
                            VerificationStatus = 0
                        },
                        new
                        {
                            Id = new Guid("82a70fce-abeb-4bc4-b51e-a72b71db2da9"),
                            ApprovedDate = new DateTime(2026, 7, 23, 6, 27, 39, 686, DateTimeKind.Utc).AddTicks(1876),
                            CompanyId = 1,
                            EntryByUserId = new Guid("30000000-0000-0000-0000-000000000001"),
                            EntryDate = new DateTime(2026, 7, 23, 6, 27, 39, 686, DateTimeKind.Utc).AddTicks(1864),
                            IsActive = true,
                            IsApproved = true,
                            IsDeleted = false,
                            RoleId = new Guid("10000000-0000-0000-0000-000000000002"),
                            UpdatedDate = new DateTime(2026, 7, 23, 6, 27, 39, 686, DateTimeKind.Utc).AddTicks(1875),
                            UserId = new Guid("30000000-0000-0000-0000-000000000001"),
                            VerificationStatus = 0
                        });
                });

            modelBuilder.Entity("UserManagement.Domain.Entities.UserStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ToDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "FromDate");

                    b.ToTable("user_statuses", "userManagement");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FromDate = new DateTime(2026, 7, 23, 6, 27, 39, 688, DateTimeKind.Utc).AddTicks(3808),
                            Remarks = "Default owner user created",
                            UserId = new Guid("30000000-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("UserManagement.Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("UserManagement.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("UserManagement.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("UserManagement.Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UserManagement.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("UserManagement.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UserManagement.Domain.Entities.Agent", b =>
                {
                    b.HasOne("UserManagement.Domain.Entities.Company", "Company")
                        .WithMany("Agents")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("UserManagement.Domain.Entities.AgentRole", b =>
                {
                    b.HasOne("UserManagement.Domain.Entities.Agent", null)
                        .WithMany("RolesForUser")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("UserManagement.Domain.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("UserManagement.Domain.Entities.AgentUser", b =>
                {
                    b.HasOne("UserManagement.Domain.Entities.Agent", "Agent")
                        .WithMany("AgentUsers")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UserManagement.Domain.Entities.User", "User")
                        .WithMany("AgentUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserManagement.Domain.Entities.CompanyRole", b =>
                {
                    b.HasOne("UserManagement.Domain.Entities.Company", null)
                        .WithMany("RolesForAgent")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("UserManagement.Domain.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Role");
                });

            modelBuilder.Entity("UserManagement.Domain.Entities.LoginLog", b =>
                {
                    b.HasOne("UserManagement.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserManagement.Domain.Entities.Menu", b =>
                {
                    b.HasOne("UserManagement.Domain.Entities.Menu", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("UserManagement.Domain.Entities.Module", b =>
                {
                    b.HasOne("UserManagement.Domain.Entities.Menu", "Menu")
                        .WithMany()
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("UserManagement.Domain.Entities.ModulePermission", b =>
                {
                    b.HasOne("UserManagement.Domain.Entities.Module", "Module")
                        .WithMany()
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UserManagement.Domain.Entities.Module", null)
                        .WithMany("ModulePermissions")
                        .HasForeignKey("ModuleId1");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("UserManagement.Domain.Entities.Role", b =>
                {
                    b.HasOne("UserManagement.Domain.Entities.Company", "Company")
                        .WithMany("Roles")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("UserManagement.Domain.Entities.User", "EntryBy")
                        .WithMany()
                        .HasForeignKey("EntryByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Company");

                    b.Navigation("EntryBy");
                });

            modelBuilder.Entity("UserManagement.Domain.Entities.RoleModulePermission", b =>
                {
                    b.HasOne("UserManagement.Domain.Entities.ModulePermission", "ModulePermission")
                        .WithMany("RoleModulePermissions")
                        .HasForeignKey("ModulePermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UserManagement.Domain.Entities.Role", "Role")
                        .WithMany("RoleModulePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModulePermission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("UserManagement.Domain.Entities.User", b =>
                {
                    b.HasOne("UserManagement.Domain.Entities.Company", "Company")
                        .WithMany("Users")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("UserManagement.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("EntryByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Company");
                });

            modelBuilder.Entity("UserManagement.Domain.Entities.UserModulePermission", b =>
                {
                    b.HasOne("UserManagement.Domain.Entities.ModulePermission", "ModulePermission")
                        .WithMany()
                        .HasForeignKey("ModulePermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UserManagement.Domain.Entities.ModulePermission", null)
                        .WithMany("UserModulePermissions")
                        .HasForeignKey("ModulePermissionId1");

                    b.HasOne("UserManagement.Domain.Entities.User", "User")
                        .WithMany("UserModulePermissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModulePermission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserManagement.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("UserManagement.Domain.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UserManagement.Domain.Entities.Role", null)
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId1");

                    b.HasOne("UserManagement.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserManagement.Domain.Entities.UserStatus", b =>
                {
                    b.HasOne("UserManagement.Domain.Entities.User", "User")
                        .WithMany("UserStatuses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserManagement.Domain.Entities.Agent", b =>
                {
                    b.Navigation("AgentUsers");

                    b.Navigation("RolesForUser");
                });

            modelBuilder.Entity("UserManagement.Domain.Entities.Company", b =>
                {
                    b.Navigation("Agents");

                    b.Navigation("Roles");

                    b.Navigation("RolesForAgent");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("UserManagement.Domain.Entities.Menu", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("UserManagement.Domain.Entities.Module", b =>
                {
                    b.Navigation("ModulePermissions");
                });

            modelBuilder.Entity("UserManagement.Domain.Entities.ModulePermission", b =>
                {
                    b.Navigation("RoleModulePermissions");

                    b.Navigation("UserModulePermissions");
                });

            modelBuilder.Entity("UserManagement.Domain.Entities.Role", b =>
                {
                    b.Navigation("RoleModulePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("UserManagement.Domain.Entities.User", b =>
                {
                    b.Navigation("AgentUsers");

                    b.Navigation("UserModulePermissions");

                    b.Navigation("UserRoles");

                    b.Navigation("UserStatuses");
                });
#pragma warning restore 612, 618
        }
    }
}
