<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\Shared.Application\Shared.Application.csproj" />
    <ProjectReference Include="..\..\Shared\Shared.Domain\Shared.Domain.csproj" />
    <ProjectReference Include="..\UserManagement.Domain\UserManagement.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Interface\" />
    <Folder Include="Common\" />
    <Folder Include="EventHandler\" />
    <Folder Include="Queries\" />
  </ItemGroup>

</Project>
